# Generated by Django 6.0 on 2025-12-29 11:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='门店全名')),
                ('desc', models.CharField(max_length=32, verbose_name='门店简称')),
            ],
            options={
                'verbose_name': '门店表',
                'verbose_name_plural': '门店表',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='banner1.png', upload_to='banner', verbose_name='图片')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.FileField(max_length=128, upload_to='icon', verbose_name='分类图标')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='分类描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='题目')),
                ('option_a', models.CharField(max_length=200, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=200, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=200, verbose_name='选项C')),
                ('option_d', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项D')),
                ('answer', models.CharField(max_length=10, verbose_name='正确答案')),
                ('course_type', models.IntegerField(choices=[(1, '皮肤学'), (2, '四维三阶问题肌'), (3, '五维筋膜'), (4, '品牌篇'), (5, '产品篇'), (6, '各类皮肤问题家居解决方案')], verbose_name='对应课程分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考核题库',
                'verbose_name_plural': '考核题库',
            },
        ),
        migrations.CreateModel(
            name='Index_Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='banner1.png', upload_to='indexan', verbose_name='宣传图片')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '首页宣传图片',
                'verbose_name_plural': '首页宣传图片',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('img', models.ImageField(default='notice.png', upload_to='notice', verbose_name='公告图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('avatar', models.FileField(max_length=128, upload_to='avator', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '店主用户表',
                'verbose_name_plural': '店主用户表',
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='welcome_fRb2uKK.png', upload_to='welcome', verbose_name='图片')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '欢迎页面',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.IntegerField(blank=True, choices=[(1, '蓝朋友'), (2, '蓝明星'), (3, 'TA创粉')], null=True)),
                ('member_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', '会员ID仅支持字母和数字')], verbose_name='会员ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号格式错误')], verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=20, null=True, verbose_name='区县')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址')),
                ('recommender1', models.CharField(blank=True, max_length=20, null=True, verbose_name='推荐人1')),
                ('recommender2', models.CharField(blank=True, max_length=20, null=True, verbose_name='推荐人2')),
                ('points', models.IntegerField(default=0, verbose_name='积分余额')),
                ('coupon_count', models.IntegerField(default=0, verbose_name='星礼券数量')),
                ('star_level', models.IntegerField(default=1, verbose_name='星级（1-5星）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, related_name='app01_user_groups', related_query_name='app01_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app01_user_permissions', related_query_name='app01_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-create_time'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.IntegerField(choices=[(1, '护肤私教认证'), (2, '线下实操考核')], verbose_name='认证类型')),
                ('name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('upload_file', models.FileField(upload_to='certification/', verbose_name='认证材料')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已驳回')], default=0, verbose_name='认证状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='认证用户')),
            ],
            options={
                'verbose_name': '线下认证',
                'verbose_name_plural': '线下认证',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('name_pinyin', models.CharField(max_length=32, null=True, verbose_name='姓名拼音')),
                ('avatar', models.ImageField(default='default.png', upload_to='collection/%Y/%m/%d', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.area', verbose_name='门店名称')),
            ],
            options={
                'verbose_name': '会员信息采集表',
                'verbose_name_plural': '会员信息采集表',
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.IntegerField(verbose_name='考核分类')),
                ('score', models.IntegerField(verbose_name='考核分数')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否通过')),
                ('exam_time', models.DateTimeField(auto_now_add=True, verbose_name='考核时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参考用户')),
            ],
            options={
                'verbose_name': '考核记录',
                'verbose_name_plural': '考核记录',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('brief_intro', models.CharField(max_length=200, verbose_name='简短介绍')),
                ('intro', models.TextField(verbose_name='详细介绍')),
                ('specs', models.TextField(blank=True, verbose_name='规格参数')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('member_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='会员价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('image', models.ImageField(upload_to='goods/', verbose_name='商品图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='课程标题')),
                ('cover_url', models.ImageField(upload_to='course/cover/', verbose_name='封面图片')),
                ('video_url', models.FileField(upload_to='course/video/', verbose_name='视频文件')),
                ('duration', models.CharField(max_length=20, verbose_name='视频时长')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.coursecategory', verbose_name='课程分类')),
            ],
            options={
                'verbose_name': '视频课程',
                'verbose_name_plural': '视频课程',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('check_in_date', models.DateField(auto_now_add=True, verbose_name='打卡日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='学习笔记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='打卡用户')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.videocourse', verbose_name='打卡课程')),
            ],
            options={
                'verbose_name': '学习打卡',
                'verbose_name_plural': '学习打卡',
                'unique_together': {('user', 'course', 'check_in_date')},
            },
        ),
    ]
