# Generated by Django 6.0 on 2026-01-09 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_index_annonce_img_recipient_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=255, verbose_name='省市区地址')),
                ('detail_address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=64, unique=True, verbose_name='订单编号')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('status', models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消')], default=0, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.address', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app01.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
    ]
