# Generated by Django 6.0 on 2026-01-14 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_user_address_address_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recommender1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recommender2',
        ),
        migrations.AddField(
            model_name='user',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_users', to=settings.AUTH_USER_MODEL, verbose_name='上级会员'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommend_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{8}$', '推荐码必须是8位数字或字母')], verbose_name='推荐码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_id',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{8}$', '会员ID必须是8位数字或字母')], verbose_name='会员ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, '蓝朋友'), (2, '蓝明星'), (3, 'TA创粉')], null=True, verbose_name='会员等级'),
        ),
    ]
