# Generated by Django 5.2.11 on 2026-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videowatchlog',
            name='point_given',
            field=models.BooleanField(default=False, verbose_name='是否已发放积分'),
        ),
    ]
