# Generated by Django 5.2.12 on 2026-03-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
    ]
