# Generated by Django 5.2.11 on 2026-02-13 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_videowatchlog_point_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='优惠券名称')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='减免金额')),
                ('min_consume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低消费门槛')),
                ('valid_days', models.IntegerField(default=90, verbose_name='有效期天数')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('end_time', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
