# Generated by Django 5.2.12 on 2026-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'ordering': ['order'], 'verbose_name': '商品媒体(图/视频)', 'verbose_name_plural': '商品媒体(图/视频)'},
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='media_type',
            field=models.SmallIntegerField(choices=[(0, '图片'), (1, '视频')], default=0, verbose_name='媒体类型'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='goods/videos/', verbose_name='商品视频'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='商品图片'),
        ),
    ]
