# Generated by Django 5.2.11 on 2026-02-13 11:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_coupon_usercoupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '优惠券模板', 'verbose_name_plural': '优惠券模板'},
        ),
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'ordering': ['-start_time'], 'verbose_name': '用户优惠券', 'verbose_name_plural': '用户优惠券'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(1, '代金券'), (2, '折扣券')], default=1, verbose_name='优惠券类型'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 13, 11, 44, 9, 143928), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='折扣系数'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='order_sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='关联订单号'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_consume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低使用门槛（元）'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='抵扣金额（元）'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='app01.coupon', verbose_name='优惠券模板'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
