# Generated by Django 5.2.12 on 2026-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_goodsimage_options_goodsimage_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='model_type',
            field=models.CharField(choices=[('lite', '快速小模型'), ('pro', '专业大模型')], default='lite', max_length=20, verbose_name='生成模型'),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='points_deducted',
            field=models.IntegerField(default=0, verbose_name='扣除积分数'),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0, verbose_name='消耗Token数'),
        ),
    ]
