# Generated by Django 5.2.11 on 2026-03-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_coupon_options_alter_usercoupon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=64, verbose_name='订单编号')),
                ('logistics_no', models.CharField(max_length=64, verbose_name='运单号')),
                ('logistics_company', models.CharField(blank=True, max_length=32, null=True, verbose_name='物流公司')),
                ('logistics_time', models.DateTimeField(verbose_name='物流节点时间')),
                ('accept_address', models.CharField(max_length=100, verbose_name='货物地点')),
                ('logistics_status', models.IntegerField(choices=[(101, '已揽收'), (201, '运送中'), (301, '派送中'), (401, '已签收'), (501, '已取消'), (601, '异常件')], verbose_name='物流状态')),
                ('logistics_status_name', models.CharField(help_text='冗余存储状态名称，如：已揽收/派送中', max_length=32, verbose_name='物流状态名称')),
                ('courier_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='派件人姓名')),
                ('courier_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='派件人联系电话')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='物流备注')),
                ('sort', models.IntegerField(default=0, verbose_name='轨迹排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_logistics', to='app01.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '快递物流轨迹',
                'verbose_name_plural': '快递物流轨迹',
                'ordering': ['sort', 'logistics_time'],
                'indexes': [models.Index(fields=['order_sn'], name='app01_expre_order_s_1979af_idx'), models.Index(fields=['logistics_no'], name='app01_expre_logisti_099e54_idx'), models.Index(fields=['logistics_time'], name='app01_expre_logisti_363f5e_idx')],
            },
        ),
    ]
