# Generated by Django 5.2.11 on 2026-03-04 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_expresslogistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expresslogistics',
            options={'ordering': ['-logistics_time', '-sort'], 'verbose_name': '快递物流轨迹', 'verbose_name_plural': '快递物流轨迹'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_point_exchange',
            field=models.BooleanField(default=False, verbose_name='是否积分兑换专用分类'),
        ),
        migrations.AddField(
            model_name='goods',
            name='point_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='积分定价=会员价×100，仅积分兑换分类商品可用', max_digits=12, verbose_name='积分定价'),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_pay_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际支付金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='point_deduct',
            field=models.IntegerField(default=0, verbose_name='抵扣积分'),
        ),
        migrations.AddField(
            model_name='order',
            name='point_deduct_money',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='积分抵扣金额'),
        ),
    ]
