# Generated by Django 6.0.4 on 2026-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_aichatmessage_model_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examrecord',
            options={'ordering': ['-exam_time'], 'verbose_name': '考核记录', 'verbose_name_plural': '考核记录'},
        ),
        migrations.AddField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='答案解析'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_type',
            field=models.IntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '判断题')], default=1, verbose_name='题型'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='score',
            field=models.IntegerField(default=5, verbose_name='单题分值'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='user_answers',
            field=models.JSONField(blank=True, null=True, verbose_name='用户答题详情'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='answer',
            field=models.CharField(help_text='多选题请用逗号分隔，如 A,B,C', max_length=10, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='course_type',
            field=models.IntegerField(choices=[(1, '皮肤学'), (2, '四维三阶问题肌'), (3, '五维筋膜'), (4, '品牌篇'), (5, '产品篇'), (6, '各类皮肤问题家居解决方案')], verbose_name='考核分类'),
        ),
    ]
