# Generated by Django 5.2.11 on 2026-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_expresslogistics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='exchange_points',
            field=models.IntegerField(default=0, verbose_name='兑换所需积分'),
        ),
    ]
