# Generated by Django 6.0.4 on 2026-05-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_examrecord_options_examquestion_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrecord',
            name='available_points',
            field=models.IntegerField(default=0, help_text='该笔积分还剩多少没被花掉（先进先出扣减）', verbose_name='剩余可用积分'),
        ),
        migrations.AddField(
            model_name='pointsrecord',
            name='expire_time',
            field=models.DateTimeField(blank=True, help_text='自获取起12个月后过期', null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_birth_date_modify',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日最后修改时间'),
        ),
        migrations.AlterField(
            model_name='pointsrecord',
            name='points',
            field=models.IntegerField(help_text='正整数=增加，负整数=扣除', verbose_name='积分值'),
        ),
        migrations.AlterField(
            model_name='pointsrecord',
            name='points_type',
            field=models.IntegerField(choices=[(1, '注册赠送'), (2, '消费赠送'), (3, '观看视频赠送'), (4, '抵扣消费'), (5, '系统扣除/过期')], verbose_name='积分类型'),
        ),
        migrations.AddIndex(
            model_name='pointsrecord',
            index=models.Index(fields=['expire_time'], name='app01_point_expire__49cef1_idx'),
        ),
    ]
