# Generated by Django 5.2.11 on 2026-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_goods_exchange_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_support_point_exchange',
            field=models.BooleanField(default=False, verbose_name='是否支持积分兑换（手动开关）'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='exchange_points',
            field=models.IntegerField(default=0, verbose_name='兑换所需积分（备用）'),
        ),
    ]
