# Generated by Django 6.0.4 on 2026-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_pointsrecord_available_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='required_level',
            field=models.IntegerField(choices=[(1, '蓝朋友0星'), (2, '蓝朋友1星'), (3, '蓝朋友2星'), (4, '蓝朋友3星'), (5, 'Ta创+')], default=1, verbose_name='最低观看会员等级'),
        ),
    ]
