# Generated by Django 5.2.11 on 2026-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_goods_is_support_point_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_support_point_exchange',
            field=models.BooleanField(default=False, verbose_name='是否支持积分兑换'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='point_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='自动按会员价×100计算，无需手动填写', max_digits=12, verbose_name='积分定价'),
        ),
    ]
