# Generated by Django 6.0.4 on 2026-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_videocourse_required_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信OpenID'),
        ),
    ]
