# Generated by Django 5.2.11 on 2026-03-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_goods_is_support_point_exchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_point_exchange',
        ),
    ]
