# Generated by Django 6.0.4 on 2026-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_user_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSenderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='发件人姓名')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='发件人手机号')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('district', models.CharField(max_length=20, verbose_name='区县')),
                ('detail_address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认发货地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '发货人/仓库地址',
                'verbose_name_plural': '发货人/仓库地址',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=0.01, help_text='用于京东物流计费计算', max_digits=8, verbose_name='体积(m³)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算', max_digits=8, verbose_name='重量(kg)'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_error_msg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='京东物流报错信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_precheck_status',
            field=models.BooleanField(default=False, verbose_name='京东预下单校验是否通过'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发件人完整地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发件人姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='发件人手机'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=8, verbose_name='单件体积(m³)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='单件重量(kg)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='物流单号/运单号'),
        ),
    ]
