# Generated by Django 5.2.11 on 2026-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_category_is_point_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_point_deducted',
            field=models.BooleanField(default=False, verbose_name='积分是否已扣减'),
        ),
    ]
