# Generated by Django 6.0.4 on 2026-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_storesenderaddress_goods_volume_goods_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jd_create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='京东下单时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东运费'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_order_status',
            field=models.CharField(blank=True, choices=[('created', '已下单'), ('cancelled', '已取消'), ('finished', '已完成')], default='', max_length=20, verbose_name='京东揽收状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='jd_error_msg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='京东报错信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='jd_precheck_status',
            field=models.BooleanField(default=False, verbose_name='京东预校验是否通过'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='支付单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付完成时间'),
        ),
    ]
