# Generated by Django 6.0.4 on 2026-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_order_jd_create_time_order_jd_freight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jd_order_status',
            field=models.CharField(blank=True, choices=[('created', '已下单/待揽收'), ('cancelled', '已取消'), ('intercepting', '拦截中'), ('intercepted', '拦截成功'), ('finished', '已妥投/已完成')], default='', max_length=20, verbose_name='京东揽收状态'),
        ),
    ]
