# Generated by Django 6.0.4 on 2026-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_order_jd_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jd_customer_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='京东客户编码'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_order_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='京东订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_order_origin',
            field=models.IntegerField(default=1, verbose_name='下单来源(固定1)'),
        ),
        migrations.AddField(
            model_name='order',
            name='jd_waybill_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='京东运单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_reference_type',
            field=models.CharField(default='20000', max_length=10, verbose_name='轨迹单据类型(固定20000)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='jd_order_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='京东订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, default='jd', max_length=50, verbose_name='物流公司'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='运单号'),
            preserve_default=False,
        ),
    ]
