# Generated by Django 6.0.4 on 2026-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_order_jd_customer_code_order_jd_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jd_latest_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='京东最新物流状态'),
        ),
    ]
