# Generated by Django 6.0.4 on 2026-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_order_jd_latest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jd_order_status',
            field=models.CharField(blank=True, choices=[('created', '已下单/待揽收'), ('cancelled', '已取消'), ('intercepting', '拦截中'), ('intercepted', '拦截成功'), ('finished', '已妥投/已完成')], default='', max_length=20, verbose_name='京东揽收状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='物流公司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='物流单号/运单号'),
        ),
    ]
