# Generated by Django 6.0.4 on 2026-06-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_order_sender_city_order_sender_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='问卷原生答案(Q1-Q8)')),
                ('skin_tags', models.JSONField(blank=True, default=list, verbose_name='智能肤质标签（优先级排序，最多3个）')),
                ('face_image_base64', models.TextField(blank=True, null=True, verbose_name='最新面部照片(Base64流)')),
                ('image_analysis', models.TextField(blank=True, null=True, verbose_name='Qwen-VL 表皮客观特征提取文本')),
                ('final_report', models.TextField(blank=True, null=True, verbose_name='小明私教综合定性报告')),
                ('skincare_plan', models.TextField(blank=True, null=True, verbose_name='小明私教终极居家方案(Markdown表格)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='首测时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profile', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户肤质档案',
                'verbose_name_plural': '用户肤质档案',
                'db_table': 'user_skin_profile',
                'ordering': ['-update_time'],
            },
        ),
    ]
