# Generated by Django 6.0.4 on 2026-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_userskinprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskinprofile',
            name='face_image_base64',
        ),
        migrations.AddField(
            model_name='userskinprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_images/%Y/%m/%d/', verbose_name='面部照片文件'),
        ),
    ]
