# Generated by Django 6.0.4 on 2026-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_remove_userskinprofile_face_image_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='volume',
        ),
        migrations.AddField(
            model_name='goods',
            name='method',
            field=models.TextField(default='', verbose_name='使用方法'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='brief_intro',
            field=models.CharField(max_length=200, verbose_name='成分'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算', max_digits=8, verbose_name='商品规格(g/瓶)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, '蓝朋友0星'), (2, '蓝朋友1星'), (3, '蓝朋友2星'), (4, '蓝朋友3星'), (5, 'Ta创+')], null=True, verbose_name='会员等级'),
        ),
    ]
