# Generated by Django 6.0.4 on 2026-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_remove_goods_volume_goods_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='specs',
            field=models.TextField(blank=True, verbose_name='注意事项'),
        ),
    ]
