# Generated by Django 6.0.4 on 2026-06-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_remove_goods_exchange_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算', max_digits=8, verbose_name='商品体积(ml/瓶)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算', max_digits=8, verbose_name='商品重量(g/瓶)'),
        ),
    ]
