# Generated by Django 6.0.4 on 2026-06-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_goods_volume_alter_goods_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['sort_order', '-update_time'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前（例如：1排在前面，99排在后面）', verbose_name='排序序号'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序序号'),
        ),
    ]
