# Generated by Django 6.0.4 on 2026-06-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_alter_category_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userskinprofile',
            options={'ordering': ['-update_time'], 'verbose_name': '被测人肤质档案', 'verbose_name_plural': '被测人肤质档案'},
        ),
        migrations.RemoveField(
            model_name='userskinprofile',
            name='face_image',
        ),
        migrations.AddField(
            model_name='userskinprofile',
            name='subject_name',
            field=models.CharField(default='', max_length=50, verbose_name='被测人姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='首测建档时间'),
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profiles', to=settings.AUTH_USER_MODEL, verbose_name='所属登录用户'),
        ),
        migrations.CreateModel(
            name='SkinPhotoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='skin_images/%Y/%m/%d/', verbose_name='面部照片文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_records', to='app01.userskinprofile', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '历史测肤照片',
                'verbose_name_plural': '历史测肤照片',
                'db_table': 'user_skin_photo_record',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
