# Generated by Django 6.0.4 on 2026-06-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_alter_userskinprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskinprofile',
            unique_together={('user', 'subject_name')},
        ),
    ]
