# Generated by Django 6.0.4 on 2026-06-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_alter_userskinprofile_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序(从小到大)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'ordering': ['sort_order', '-create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='required_level',
        ),
        migrations.AddField(
            model_name='videocourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.coursecategory', verbose_name='所属分类'),
        ),
    ]
