# Generated by Django 6.0.4 on 2026-06-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_coursecategory_remove_videocourse_required_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['sort_order', '-create_time'], 'verbose_name': '视频分类', 'verbose_name_plural': '视频分类'},
        ),
    ]
