# Generated by Django 6.0.4 on 2026-06-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_alter_coursecategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='订单编号')),
                ('target_level', models.IntegerField(verbose_name='目标等级 (2-5)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='升级用户')),
            ],
            options={
                'verbose_name': '会员升级订单',
                'verbose_name_plural': '会员升级订单',
            },
        ),
    ]
