# Generated by Django 6.0.4 on 2026-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_upgradeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会籍到期时间'),
        ),
    ]
