# Generated by Django 6.0.4 on 2026-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_user_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
