# Generated by Django 6.0.4 on 2026-06-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_user_avatar_alter_banner_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='video_url',
            field=models.CharField(help_text='请填入专属视频服务器下的相对路径，例如：/rspf/rspf1/output_rspf1.m3u8', max_length=255, verbose_name='视频播放路径'),
        ),
    ]
