# Generated by Django 6.0.4 on 2026-06-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_alter_videocourse_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourse',
            name='duration',
        ),
    ]
