# Generated by Django 6.0.4 on 2026-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_remove_videocourse_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourse',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='videocourse',
            name='duration',
            field=models.CharField(default='1', max_length=20, verbose_name='视频时长'),
            preserve_default=False,
        ),
    ]
