# Generated by Django 6.0.4 on 2026-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_remove_videocourse_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='会员权益长图', max_length=50, verbose_name='标题')),
                ('image', models.ImageField(upload_to='privilege/', verbose_name='权益图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用当前图')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员权益配置',
                'verbose_name_plural': '会员权益配置',
                'ordering': ['-update_time'],
            },
        ),
    ]
