# Generated by Django 6.0.4 on 2026-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_memberprivilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='duration',
            field=models.IntegerField(max_length=20, verbose_name='视频时长'),
        ),
    ]
