# Generated by Django 6.0.4 on 2026-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_alter_videocourse_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, help_text='前端会按此数字从小到大正序排列（如 1, 2, 3...）', verbose_name='视频序号/集数'),
        ),
    ]
