# Generated by Django 6.0.4 on 2026-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_videocourse_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['sort_order', '-update_time'], 'verbose_name': '商品/线下项目', 'verbose_name_plural': '商品/线下项目'},
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.SmallIntegerField(choices=[(1, '实体商品'), (2, '线下项目')], default=1, verbose_name='商品/项目类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='service_times',
            field=models.IntegerField(default=1, help_text='仅对线下项目有效，买一次包含几次服务', verbose_name='项目包含次数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brief_intro',
            field=models.CharField(max_length=200, verbose_name='成分/简介'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='method',
            field=models.TextField(blank=True, verbose_name='使用方法'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价/零售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算（线下项目可忽略）', max_digits=8, verbose_name='商品体积(ml/瓶)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算（线下项目可忽略）', max_digits=8, verbose_name='商品重量(g/瓶)'),
        ),
    ]
