# Generated by Django 6.0.4 on 2026-06-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_alter_goods_options_goods_goods_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['sort_order', '-update_time'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_type',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='service_times',
        ),
        migrations.AlterField(
            model_name='goods',
            name='brief_intro',
            field=models.CharField(max_length=200, verbose_name='成分'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='method',
            field=models.TextField(verbose_name='使用方法'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算', max_digits=8, verbose_name='商品体积(ml/瓶)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='用于京东物流计费计算', max_digits=8, verbose_name='商品重量(g/瓶)'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='duration',
            field=models.IntegerField(default=10, verbose_name='视频时长'),
        ),
        migrations.CreateModel(
            name='OfflineServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '待客户确认'), (1, '已完成')], default=0, verbose_name='状态')),
                ('rating', models.SmallIntegerField(blank=True, help_text='1-5星', null=True, verbose_name='星级打分')),
                ('review_content', models.TextField(blank=True, null=True, verbose_name='评价文字')),
                ('review_images', models.JSONField(blank=True, help_text="存储图片URL列表，如 ['url1', 'url2']", null=True, verbose_name='评价图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='店长发起时间')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='客户确认时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='评价提交时间')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_records', to=settings.AUTH_USER_MODEL, verbose_name='服务店长')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods', verbose_name='服务项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '服务与评价记录',
                'verbose_name_plural': '服务与评价记录',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserOfflineProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_times', models.IntegerField(default=0, verbose_name='总次数')),
                ('remain_times', models.IntegerField(default=0, verbose_name='剩余次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods', verbose_name='线下项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_projects', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
            ],
            options={
                'verbose_name': '用户项目资产',
                'verbose_name_plural': '用户项目资产',
            },
        ),
    ]
