# Generated by Django 6.0.4 on 2026-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_alter_goods_options_remove_goods_goods_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.SmallIntegerField(choices=[(1, '实体商品'), (2, '线下项目')], default=1, verbose_name='商品/项目类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='service_times',
            field=models.IntegerField(default=1, help_text='仅对线下项目有效，买一次包含几次服务', verbose_name='项目包含次数'),
        ),
    ]
