# Generated by Django 6.0.4 on 2026-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_goods_goods_type_goods_service_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.SmallIntegerField(choices=[(1, '居家产品'), (2, '线下项目')], default=1, verbose_name='商品/项目类型'),
        ),
    ]
