# Generated by Django 6.0.4 on 2026-06-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0040_alter_goods_goods_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userofflineproject',
            options={'verbose_name': '线下项目资产', 'verbose_name_plural': '线下项目资产'},
        ),
    ]
