# Generated by Django 6.0.4 on 2026-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0041_alter_userofflineproject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userofflineproject',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约到店时间'),
        ),
        migrations.AddField(
            model_name='userofflineproject',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已预约_待到店'), (1, '核销中_待确认'), (2, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
