# Generated by Django 6.0.4 on 2026-06-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0043_offlineservicerecord_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='qualification',
            field=models.TextField(blank=True, verbose_name='产品规格(g/ml)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brief_intro',
            field=models.CharField(blank=True, max_length=200, verbose_name='核心成分'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='specs',
            field=models.TextField(blank=True, verbose_name='适合肤质'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sn',
            field=models.CharField(max_length=64, unique=True, verbose_name='商户订单编号'),
        ),
    ]
