# Generated by Django 6.0.4 on 2026-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0044_goods_qualification_alter_goods_brief_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='fuc',
            field=models.TextField(default='', verbose_name='产品功效'),
            preserve_default=False,
        ),
    ]
