# Generated by Django 6.0.4 on 2026-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0045_goods_fuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fuc',
            field=models.CharField(verbose_name='产品功效'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='qualification',
            field=models.CharField(blank=True, verbose_name='产品规格(g/ml)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='specs',
            field=models.CharField(blank=True, verbose_name='适合肤质'),
        ),
    ]
