# Generated by Django 6.0.4 on 2026-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0046_alter_goods_fuc_alter_goods_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brief_intro',
            field=models.TextField(blank=True, max_length=200, verbose_name='核心成分'),
        ),
    ]
