# Generated by Django 6.0.4 on 2026-06-28 16:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0047_alter_goods_brief_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rebate_done',
            field=models.BooleanField(default=False, verbose_name='是否已返佣'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='账户余额'),
        ),
    ]
