# Generated by Django 6.0.4 on 2026-06-29 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0048_order_rebate_done_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rebate_done',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.CreateModel(
            name='WithdrawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_bill_no', models.CharField(max_length=64, unique=True, verbose_name='商户单号')),
                ('transfer_bill_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信转账单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额')),
                ('status', models.IntegerField(choices=[(0, '待财务审核'), (1, '打款中(待用户微信确认)'), (2, '打款成功'), (3, '已拒绝/打款失败')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('audit_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='审核备注')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_withdraws', to=settings.AUTH_USER_MODEL, verbose_name='审核人(财务)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to=settings.AUTH_USER_MODEL, verbose_name='提现用户')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'db_table': 'withdraw_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
