# Generated by Django 6.0.4 on 2026-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0050_commissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='normal', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='register_data',
            field=models.JSONField(blank=True, null=True, verbose_name='注册暂存数据'),
        ),
    ]
