# Generated by Django 6.0.4 on 2026-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0052_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrecord',
            options={'ordering': ['-create_time'], 'verbose_name': '佣金收益流水', 'verbose_name_plural': '佣金收益流水'},
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='佣金金额'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记账时间'),
        ),
    ]
