# Generated by Django 6.0.4 on 2026-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0053_alter_commissionrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frozen_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='冻结中余额（提现中）'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawable_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='可提现余额'),
        ),
    ]
