# Generated by Django 6.0.4 on 2026-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0054_user_frozen_balance_user_withdrawable_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrecord',
            name='package_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='微信收款包'),
        ),
    ]
