# Generated by Django 6.0.4 on 2026-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0055_withdrawrecord_package_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.SmallIntegerField(choices=[(1, '居家产品'), (2, '线下项目'), (3, '京东物流')], default=1, verbose_name='商品/项目类型'),
        ),
    ]
