# Generated by Django 6.0.4 on 2026-07-07 10:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0056_alter_goods_goods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='返佣计算基数(真金白银)'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_deduct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='优惠券抵扣金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='电子账户支付金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='wechat_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='第三方支付金额(微信/支付宝)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.IntegerField(blank=True, choices=[(1, '微信支付'), (2, '线下支付'), (3, '电子账户支付'), (4, '混合支付')], null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='final_report',
            field=models.TextField(blank=True, null=True, verbose_name='蓝博士私教综合定性报告'),
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='skincare_plan',
            field=models.TextField(blank=True, null=True, verbose_name='私教终极居家方案(Markdown表格)'),
        ),
        migrations.CreateModel(
            name='RechargeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：充1000送200元代金券', max_length=100, verbose_name='活动名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='需充值金额(实付)')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='额外赠送金额(进入赠金账户)')),
                ('gift_coupon_num', models.IntegerField(default=1, verbose_name='赠送代金券张数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序(越小越靠前)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gift_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.coupon', verbose_name='赠送的代金券')),
            ],
            options={
                'verbose_name': '储值套餐',
                'verbose_name_plural': '储值套餐',
                'ordering': ['sort_order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=64, unique=True, verbose_name='充值单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应付金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '充值成功'), (2, '已取消')], default=0, verbose_name='支付状态')),
                ('pay_method', models.IntegerField(choices=[(1, '微信支付'), (2, '模拟支付')], default=1, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信支付流水号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.rechargeactivity', verbose_name='参与的储值套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_orders', to=settings.AUTH_USER_MODEL, verbose_name='充值用户')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='本金余额')),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='赠送金余额')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总余额')),
                ('status', models.BooleanField(default=True, verbose_name='账户状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后变动时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户电子钱包',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=64, unique=True, verbose_name='交易流水号')),
                ('order_sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='关联业务订单号')),
                ('transaction_type', models.SmallIntegerField(choices=[(1, '充值'), (2, '消费扣款'), (3, '退款返还'), (4, '后台修改')], verbose_name='变动类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动总金额')),
                ('principal_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本金变动')),
                ('bonus_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='赠金变动')),
                ('after_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动后总余额')),
                ('remark', models.CharField(max_length=255, verbose_name='变动说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app01.userwallet', verbose_name='对应钱包')),
            ],
        ),
    ]
