# Generated by Django 6.0.4 on 2026-07-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0057_order_commission_base_order_coupon_deduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': '电子账户流水'},
        ),
    ]
