# Generated by Django 6.0.4 on 2026-07-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0058_alter_wallettransaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwallet',
            options={'verbose_name': '用户电子钱包', 'verbose_name_plural': '用户电子钱包'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': '电子账户流水', 'verbose_name_plural': '电子账户流水'},
        ),
    ]
