# Generated by Django 6.0.4 on 2026-07-09 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0059_alter_userwallet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '门店负责人', 'verbose_name_plural': '门店负责人'},
        ),
        migrations.AddField(
            model_name='area',
            name='belong_to_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_offline_stores', to=settings.AUTH_USER_MODEL, verbose_name='所属Ta创+大老板'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfill_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_fulfill_orders', to=settings.AUTH_USER_MODEL, verbose_name='履约方(发货的Ta创+)'),
        ),
        migrations.AddField(
            model_name='user',
            name='root_enterprise',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_downline_users', to=settings.AUTH_USER_MODEL, verbose_name='归属的Ta创+(算发货用)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='门店负责人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(max_length=128, upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='企业/公司名称')),
                ('credit_code', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='统一社会信用代码')),
                ('corporate_bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业对公账户')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='开户行')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用结算')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profiles', to=settings.AUTH_USER_MODEL, verbose_name='所属Ta创+')),
            ],
            options={
                'verbose_name': 'Ta创+企业档案',
                'verbose_name_plural': 'Ta创+企业档案',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='app01.enterpriseprofile', verbose_name='归属企业账户'),
        ),
    ]
