# Generated by Django 6.0.4 on 2026-07-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0060_alter_userinfo_options_area_belong_to_boss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='线下认证长图', max_length=50, verbose_name='标题')),
                ('image', models.ImageField(upload_to='certification/', verbose_name='认证图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用当前图')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线下认真配置',
                'verbose_name_plural': '线下认真配置',
                'ordering': ['-update_time'],
            },
        ),
    ]
