# Generated by Django 6.0.4 on 2026-07-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0061_offlinecertification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinecertification',
            options={'ordering': ['-update_time'], 'verbose_name': '线下认证配置', 'verbose_name_plural': '线下认证配置'},
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
