# Generated by Django 6.0.4 on 2026-08-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0062_alter_offlinecertification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use_ai',
            field=models.BooleanField(default=False, verbose_name='允许使用智能蓝博士'),
        ),
    ]
