# Generated by Django 6.0.4 on 2026-08-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0063_user_can_use_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coupon_count',
            field=models.IntegerField(default=0, verbose_name='优惠券数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='root_enterprise',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_downline_users', to=settings.AUTH_USER_MODEL, verbose_name='归属的Ta创+(算发货用)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, '蓝朋友'), (2, '蓝朋友1星'), (3, '蓝朋友2星'), (4, '蓝朋友3星'), (5, '蓝朋友4星'), (6, '蓝朋友5星'), (7, 'Ta创+')], null=True, verbose_name='会员等级'),
        ),
    ]
