# Generated by Django 6.0.4 on 2026-09-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0065_alter_user_options_remove_user_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(help_text='默认根据模板有效期自动计算，管理员可手动修改延期', verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='系统自动记录，不可更改', verbose_name='领取/发放时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='used_time',
            field=models.DateTimeField(blank=True, help_text='核销时系统自动记录', null=True, verbose_name='实际使用时间'),
        ),
    ]
